export const english_letters = [
  { letter: 'A', emoji: 'اللّٰه', word: 'Allah' },
  { letter: 'B', emoji: '📿', word: 'Bismillah' },
  { letter: 'C', emoji: '👳‍♂️', word: 'Caliph' },
  { letter: 'D', emoji: '🤲', word: 'Dua' },
  { letter: 'E', emoji: '✨', word: 'Eid' },
  { letter: 'F', emoji: '🌅', word: 'Fajr' },
  { letter: 'G', emoji: '🐐', word: 'Goat' },
  { letter: 'H', emoji: '🕋', word: 'Hajj' },
  { letter: 'I', emoji: '🕌', word: 'Islam' },
  { letter: 'J', emoji: '🍏', word: 'Jannah' },
  { letter: 'K', emoji: '🤴', word: 'King' },
  { letter: 'L', emoji: '💡', word: 'Light' },
  { letter: 'M', emoji: '🌙', word: 'Moon' },
  { letter: 'N', emoji: '👃', word: 'Nose' },
  { letter: 'O', emoji: '🌊', word: 'Ocean' },
  { letter: 'P', emoji: '🙏', word: 'Peace' },
  { letter: 'Q', emoji: '📖', word: 'Quran' },
  { letter: 'R', emoji: '🕌', word: 'Ramadan' },
  { letter: 'S', emoji: '🌟', word: 'Star' },
  { letter: 'T', emoji: '🌳', word: 'Tree' },
  { letter: 'U', emoji: '☂️', word: 'Umbrella' },
  { letter: 'V', emoji: '🏞️', word: 'Valley' },
  { letter: 'W', emoji: '🍉', word: 'Watermelon' },
  { letter: 'X', emoji: '❌', word: 'X-Ray' },
  { letter: 'Y', emoji: '🍋', word: 'Yellow' },
  { letter: 'Z', emoji: '🦓', word: 'Zebra' }
];
